slov_v_stringu = str({
        "Kód obce": '593711', 
        "Název obce": 'Znojmo', 
        "Voliči v seznamu": '27 255',
        "Vydané obálky": '16 292', 
        "Platné hlasy": '16 179', 
        "Občanská demokratická strana": '1 644',
        "Řád národa - Vlastenecká unie": '21', 
        "CESTA ODPOVĚDNÉ SPOLEČNOSTI": '7', 
        "Česká str.sociálně demokrat.": '1 725', 
        "Radostné Česko": '8',
        "STAROSTOVÉ A NEZÁVISLÍ": '506', 
        "Komunistická str.Čech a Moravy": '1 431',
        "Strana zelených": '175', 
        "ROZUMNÍ-stop migraci,diktát.EU": '115',
        "Strana svobodných občanů": '257', 
        "Blok proti islam.-Obran.domova": '18',
        "Občanská demokratická aliance": '38',
        "Česká pirátská strana": '1 255',
        "Referendum o Evropské unii": '6', 
        "TOP 09": '507', "ANO 2011": '5 023',
        'Dobrá volba 2016': '16', 
        'SPR-Republ.str.Čsl. M.Sládka': '23', 
        'Křesť.demokr.unie-Čs.str.lid.': '896', 
        'Česká strana národně sociální': '3',
        'REALISTÉ': '68', 'SPORTOVCI': '11', 
        'Dělnic.str.sociální spravedl.': '16',
        'Svob.a př.dem.-T.Okamura (SPD)': '2 316' , 
        'Strana Práv Občanů': '88', 
        'Národ Sobě': '6'
    })
slov_v_stringu = slov_v_stringu.replace("'", "\"")
print(slov_v_stringu)